name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@2
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: .
